name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check-arm64:
    name: Check (aarch64-apple-ios)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios
      - name: Cargo Check (arm64)
        run: cargo check --target aarch64-apple-ios

  check-native:
    name: Check (Native & Dependencies)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Cargo Check
        run: cargo check
